
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 13 20:58:43 CST 2011
//----------------------------------------------------

package parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 42;
  public static final int FUNCTION = 10;
  public static final int GE = 37;
  public static final int UMINUS = 40;
  public static final int LPAREN = 20;
  public static final int INT = 45;
  public static final int ARRAY = 13;
  public static final int MINUS = 39;
  public static final int FOR = 4;
  public static final int RPAREN = 21;
  public static final int SEMICOLON = 26;
  public static final int AND = 31;
  public static final int LT = 34;
  public static final int TYPE = 12;
  public static final int NIL = 2;
  public static final int IN = 8;
  public static final int OR = 30;
  public static final int COMMA = 27;
  public static final int PLUS = 38;
  public static final int ASSIGN = 29;
  public static final int IF = 14;
  public static final int ID = 43;
  public static final int DOT = 28;
  public static final int LE = 35;
  public static final int OF = 18;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NEQ = 33;
  public static final int BREAK = 6;
  public static final int EQ = 32;
  public static final int LBRACK = 24;
  public static final int TIMES = 41;
  public static final int COLON = 19;
  public static final int LBRACE = 22;
  public static final int ELSE = 16;
  public static final int RBRACK = 25;
  public static final int TO = 5;
  public static final int WHILE = 3;
  public static final int LET = 7;
  public static final int THEN = 15;
  public static final int RBRACE = 23;
  public static final int END = 9;
  public static final int STRING = 44;
  public static final int GT = 36;
  public static final int VAR = 11;
  public static final int DO = 17;
}

